server:
  port: 10090

spring:
  application:
    name: hospitalService
  datasource:
    url: jdbc:postgresql://db:5432/hospitalDb # db, localhost
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Burayı güncelledik
        validation:
          mode: none # Değiştirilecek
      jakarta:
        persistence:
          validation:
            mode: none # Burayı ekliyoruz
    show-sql: true
  web:
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:5173
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
